import { JSXFactory } from 'jsxFactories/virtualDomFactory';

interface VDomPageElementHandler {
  (attributes: {}, contents: any): any;
}

export const VDomPage: VDomPageElementHandler = ({ }, contents) => {
    const a = <div id='vdompage'>
      <h2>This page produced with vdom</h2>
      <p>Generated by: </p>
    </div>;
    return(a);
}