import { h, VNode } from 'maquette';
import { FactoryType } from 'globals';

const createElement = (tag:any, props:any, ...children:any): VNode => {
  if ((children.length === 1) && (children[0] === 'Generated by: ')) {
    children = ['Generated by: Maquette']
  }
  const r =  h(tag, props, [...children]);

  if (typeof tag === 'function') {
    return tag(props, children);
  }
  return r;

}

export const JSXFactory = {
  factoryType: FactoryType.Maquette,
  createElement
}

